#!D:/Users/Administrator/AppData/Local/Programs/Python/Python36-32/python.exe
# -*- coding: UTF-8 -*-
print ("Content-type:text/html")
print ()
print ("<html lang='en'>")
print ('<head>')
print ('<meta charset="utf-8">')
print ('<meta http-equiv="X-UA-Compatible" content="IE=edge">')
print ('<meta name="description" content="">')
print ('<meta name="keywords" content="">')
print ('<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">')
print ('<title> Hello Word - myfirst！</title>')
print ('</head>')
print ('<body>')
print ('<h2>Hello Word! 我是来自菜鸟教程的第一CGI程序</h2>')
print ('</body>')
print ('</html>')